#!/bin/bash

. ~/.files-balamah/config/scripts/functions.sh

declare -A enUa=(
	["q"]="й" ["w"]="ц" ["e"]="у" ["r"]="к" ["t"]="е" ["y"]="н" ["u"]="г"
	["i"]="ш" ["o"]="щ" ["p"]="з" ["["]="х" ["]"]="ї" ["a"]="ф" ["s"]="і"
	["d"]="в" ["f"]="а" ["g"]="п" ["h"]="р" ["j"]="о" ["k"]="л" ["l"]="д"
	[";"]="ж" ["'"]="є" ["z"]="я" ["x"]="ч" ["c"]="с" ["v"]="м" ["b"]="и"
	["n"]="т" ["m"]="ь" [","]="б" ["."]="ю" ["/"]="." ["•"]=" " [" "]="•"
	["\`"]="\''")

declare -A uaEn=(
	["й"]="q" ["ц"]="w" ["у"]="e" ["к"]="r" ["е"]="t" ["н"]="y" ["г"]="u"
	["ш"]="i" ["щ"]="o" ["з"]="p" ["х"]="[" ["ї"]="]" ["ф"]="a" ["і"]="s"
	["в"]="d" ["а"]="f" ["п"]="g" ["р"]="h" ["о"]="j" ["л"]="k" ["д"]="l"
	["ж"]=";" ["є"]="'" ["я"]="z" ["ч"]="x" ["с"]="c" ["м"]="v" ["и"]="b"
	["т"]="n" ["ь"]="m" ["б"]="," ["ю"]="." ["."]="/" [" "]="•" ["•"]=" "
)

text=$(cat /tmp/.files-balamah/recent/layout-converter | \
		   dmenu -p " Enter text to convert" | rip | \
		   tr '[:upper:]' '[:lower:]')

letters=$(echo "$text" | sed "s/ /•/g" | grep -o .)
if [[ "$letters" =~ [йцукенгшщзхїфівапролджєячсмитьбю] ]]; then
	output=$(for symbol in $letters; do echo -n "${uaEn[$symbol]}"; done)
else
	output=$(for symbol in $letters; do echo -n "${enUa[$symbol]}"; done)
fi

[ -z "$output" ] && exit || \
	echo "$text" > /tmp/.files-balamah/recent/layout-converter

~/.config/scripts/notify-send-copy \
	"${0##*/}" "Converted text is \"$output\"" "$output"
