#!/bin/sh

echo | dmenu -p " Enter password length" | \
	xargs python3 ~/.config/scripts/python/passwdgen.py "$length" | \
	xargs -I "%" ~/.config/scripts/notify-send-copy "${0##*/}" \
	"Password successfully generated" "%"
