#!/bin/bash

. ~/.files-balamah/settings.conf

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice xorg programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done

	unset f
fi

# launch startup scripts
startup() {
	# $1 :: directory with scripts

	[ -z "$1" ] && return 1

	find "$1" -type f -executable | sort | xargs -I "%" bash "%" &
}

startup ~/.config/scripts/startup/
[ "$enableLocalStartupScripts" = 'yes' ] && startup "$localStartupScripts"

# entry point for window managers
case "$profile" in
	'qtile') exec qtile start                             ;;
	'exwm')  exec emacs -mm --debug-init                  ;;
	*)       [ "$profile" != 'no-wm' ] && exec "$profile" ;;
esac
