#!/bin/sh

. ~/.files-balamah/settings.conf

# couldn't make elegant unfortunately
if [ "$enableSpotifyFlatpak" = 'no' ]; then
	LD_PRELOAD=$HOME/.spotify-adblock/spotify-adblock.so spotify
else
	flatpak run --command=sh com.spotify.Client -c \
		'eval "$(sed s#LD_PRELOAD=#LD_PRELOAD=$HOME/.spotify-adblock/spotify-adblock.so:#g /app/bin/spotify)"'
fi
