#!/bin/sh

. ~/.files-balamah/settings.conf 

ffplay -window_title webcam /dev/video0 -video_size "$videoSize" \
	-max_delay 0 -max_probe_packets 1 -analyzeduration 0 \
	-flags +low_delay -fflags +nobuffer
