#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X
bspc query -M | sort | \
	while read monitor; do
		bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9
		# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
	done

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
 
bspc rule -a firefox desktop='^1' #.monitor = 1
bspc rule -a Spotify desktop='^2' #.monitor = 1
bspc rule -a obs desktop='^8' #.monitor = 1
bspc rule -a DBeaver desktop='^8' #.monitor = 1
bspc rule -a Soundux desktop='^8' #.monitor = 1

bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a ViberPC desktop='^4' #.monitor = 0
bspc rule -a discord desktop='^4' #.monitor = 0

bspc rule -a Code desktop='^6' #.monitor = 0
bspc rule -a jetbrains-pycharm-ce desktop='^6' #.monitor = 0

bspc rule -a Editors desktop='^8'
bspc rule -a Minecraft Launcher desktop='^8' #.monitor = 0
bspc rule -a VirtualBox Manager desktop='^8' #.monitor = 0
bspc rule -a openrgb desktop='^8' #.monitor = 0
bspc rule -a steam desktop='^8' #.monitor = 0
bspc rule -a Pinta desktop='^8' #.monitor = 0
bspc rule -a kdenlive desktop='^8' #.monitor = 0

bspc rule -a zoom desktop='9' #.monitor = 0
