#!/bin/bash

. ~/.files-balamah/settings.conf

[ "$enableWallpapers" != 'yes' ] && exit

wallpapersFind() {
	# $1 :: prefix (optional)

	find $wallpapersPath -type f \
			   -name "$1*.jpg" -o \
			   -name "$1*.png" -o \
			   -name "$1*.jpeg"
}

wsource=$(wallpapersFind)

[ "$enableBrightWallpapersMorning" = 'yes' ] && \
	[[ "$(date +'%H:%M')" < "$brightWallpapersLimitTime" ]] && \
	wsource=$(wallpapersFind "bright")

[ "$enableRandomWallpapers" = 'yes' ] && \
	file=$(echo "$wsource" | shuf -n 1 | sed "s@\~@$HOME@g") || \
	file=$(cat ~/.cache/wal/wal)

[ -z "$file" ] && notify-send "${0##*/}" "no wallpaper to set" && exit 1

feh --no-fehbg --bg-fill "$file"
echo "$file" > /tmp/.files-balamah/20-curWallpaper.tmp
echo "$file" >> /tmp/.files-balamah/recent/wallpapers

dunstify "${0##*/}" 'wallpaper has just changed' -r 5555 -u low -I "$file"

~/.config/scripts/wal-sync
