#!/bin/bash

# Colors are here.
# - 1 :: red
# - 2 :: green
# - 3 :: yellow
# - 4 :: cyan
# - 5 :: purple
# - 6 :: aqua
# - 7 :: light grey

. ~/.files-balamah/config/scripts/widgets/start/resources.sh 
. ~/.files-balamah/settings.conf 

# PWD=$sxwDirectory
# cd $PWD

# Background
#              x                   y    w     h     override-redirect  font-size  symbol  color  command
iconbutton $((430 + offsetx))  260  1060  560   1                  60        ''       6      '' &
sleep 0.1

# Special widgets
#             xpos                ypos width   height    overide-redirect font-size
volume        $((855 + offsetx))  570  55      240       1                18  &
quote         $((1030 + offsetx)) 380  450     210       1                14  &
playerctlplay $((564 + offsetx))  510  50      50        1                30  &
# bin/planets      $((1030 + offsetx)) 600  240     150       1                30  &
# bin/mpdinfo      $((440 + offsetx))  440  300     60        1                18  &
# bin/brightness   $((810 + offsetx))  380  100     50        1                21  &

# Icon buttons
logo=$(~/.config/scripts/get/distro/logo)
color=$(~/.config/scripts/get/distro/color-logo)

#          x                   y    w   h     override-redirect   font-size  symbol  color      command
iconbutton $((805 + offsetx))  380  50  50    1                   18                3          'emacsclient -c -s "default" ~/.files-balamah/settings.conf ' &
iconbutton $((860 + offsetx))  380  50  50    1                   18                3          'emacsclient -c -s "default" ~/.files-balamah/README.org ' &
iconbutton $((440 + offsetx))  510  50  50    1                   25                1          '~/.config/scripts/app-audio-control previous' & 
iconbutton $((502 + offsetx))  510  50  50    1                   25                2          '~/.config/scripts/app-audio-control rewind -' &
iconbutton $((626 + offsetx))  510  50  50    1                   25                2          '~/.config/scripts/app-audio-control rewind +' &
iconbutton $((688 + offsetx))  510  50  50    1                   25                1          '~/.config/scripts/app-audio-control next' &
iconbutton $((440 + offsetx))  570  75  73    1                   35                3          '~/.config/scripts/dmenu/shutdown reboot' &
iconbutton $((440 + offsetx))  653  75  73    1                   35                1          '~/.config/scripts/dmenu/shutdown shutdown' &
iconbutton $((440 + offsetx))  738  75  73    1                   35                2          "~/.config/scripts/dmenu/$profile/logout" &
iconbutton $((920 + offsetx))  270  100  100  1                   50                1          'firefox' &
iconbutton $((920 + offsetx))  380  100  100  1                   50                5          'emacsclient -c -s "default"' &
iconbutton $((920 + offsetx))  490  100  100  1                   35         󰃀       4          '~/.config/scripts/dmenu/bookmarks ' &
iconbutton $((920 + offsetx))  600  100  100  1                   50                2          'emacsclient -c -s "default" -a "org-agenda" --eval "(org-agenda-delete-windows)"' &
iconbutton $((920 + offsetx))  710  100  100  1                   35                3          'emacsclient -c -s "default" -a "org-capture" --eval "(org-capture)"' &
iconbutton $((750 + offsetx))  440  160  120  1                   60                4          '~/.config/scripts/app-audio-control shift shift' &
iconbutton $((1290 + offsetx)) 600  190  150  1                   60                4          '~/.local/bin/tabbed-st -e nmtui' &
iconbutton $((525 + offsetx))  570  150  115  1                   110        $logo   $color     '~/.config/scripts/dmenu/desktop-entry-launch' &
iconbutton $((1450 + offsetx)) 270   30   30  1                   12         󰅖       1          "~/.config/scripts/widgets/kill-widgets $0" &
iconbutton $((1450 + offsetx)) 305   30   30  1                   12                2          'slock' &
iconbutton $((1450 + offsetx)) 340   30   30  1                   18                3          "~/.config/scripts/dmenu/daemon-launcher " &
iconbutton $((1430 + offsetx)) 760   50   50  1                   25         󰧼       1          "~/.config/scripts/kill-programs " &

# Info widgets
#          x                   y    w    h     override-redirect font-size   color  update time   command
infowidget $((440 + offsetx))  440  300  60    1                 18          4      1             'echo -n "󰝚 " && ~/.config/scripts/get/track' &
infowidget $((700 + offsetx))  380  100  50    1                 18          2      10            'echo -n " " && ~/.config/scripts/get/battery' &
infowidget $((700 + offsetx))  270  210  100   1                 50          1      10            'date +"%H:%M"' &
infowidget $((525 + offsetx))  695  150  55    1                 18          3      2             'echo -n " " && ~/.config/scripts/get/cpu-load ' &
infowidget $((525 + offsetx))  760  150  50    1                 18          3      2             'echo -n " " && ~/.config/scripts/get/ram-usage' &
infowidget $((685 + offsetx))  570  160  115   1                 40          2      3600          'echo -n "󰛃" && ~/.config/scripts/get/distro/packages-update' &
infowidget $((1030 + offsetx)) 270  413  100   1                 30          5      3600          '~/.config/scripts/get/greeting' &
infowidget $((685 + offsetx))  695  160  115   1                 30          1      3600          'date +"%d %b"' &
infowidget $((1030 + offsetx)) 760  390  50    1                 20          3      10            'echo -n " " && ~/.config/scripts/get/uptime' &
infowidget $((440 + offsetx))  270  250  160   1                 23          2      10            '~/.config/scripts/get/weather' &
infowidget $((1030 + offsetx)) 600  250  150   1                 15          3      1             '~/.config/scripts/get/login-dashboard-info' &
