#!/bin/bash

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

. ~/.files-balamah/settings.conf 
. ~/.config/scripts/functions.sh 

notify() {
	notify-send 'sxiv' "$@"
}

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | \
		while read file; do
		case "$(file -b -i "$file")" in
			image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
			*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

setWallpaper() {
	echo "$1" >> /tmp/.files-balamah/recent/wallpapers

	python3 -m pywal -i "$1" && \
		echo "$1" > /tmp/.files-balamah/20-curWallpaper.tmp && \
		bash ~/.config/scripts/wal-sync &
}

fileManagerOpen() {
	# $1 - $file
	
	file="$1"
	echo "${file%/*}" | sed "s@^\~@$HOME@g;s@ @\\\ @g" | \
		xargs ~/.local/bin/tabbed-st ranger &
}

rename() {
	# $1 - $file

	file="$1"
	directory=$(dirname "$file")

	name=$(echo "${file##*/}" | dmenu -p ' Enter name to rename the file' | \
		sed "s/  / /g;s@ @\\\ @g;")

	[ -z "$name" ] && return

	mv "$file" "$directory/$name" && \
		notify "image successfully renamed to $name" || \
		notify "image failed to rename to $name"
}

transfer() {
	# $1 - cp, mv
	# $2 - $file

	case "$1" in
		"cp") verb="copy" ;;
		"mv") verb="move" ;;
	esac

	file=sxiv-directories.dmenu-ignore
	[ ! -f "$bookmarksPath/$file" ] && \
		bookmarks="$standardBookmarksPath/$file" || \
		bookmarks="$bookmarksPath/$file"

	destinationDirectory=$(br "$bookmarks" | \
		dmenu -p " Choose destination directory to $verb" -l 20 | awk '{print $2}')

	[ -z "$destinationDirectory" ] && return

	file=$(echo "$2" | sed "s@ @\\\ @g")
	eval "$1" "$file" "$destinationDirectory" && \
		notify "image successfully $1ed to $destinationDirectory" || \
		notify "failed to $verb image to $destinationDirectory"
}

clipboardCopy() {
	echo "$1" | xclip -selection clipboard
}

while read file; do
	case "$1" in
		"C-w")      setWallpaper "$file"  ;;
		"C-v")      clipboardCopy "$file" ;;
		"C-b")      clipboardCopy "${file##*/}" ;;
		"C-c")      xclip -selection clipboard -target image/png "$file" ;;

		"C-x")		fileManagerOpen "$file" ;;
		"C-d")		rm "$file" ;; 
		"C-r")		rename "$file" ;;
		"C-a")		transfer mv "$file" ;;
		"C-q")		transfer cp "$file" ;;
	esac
done
